spring:
  application:
    name: hhplus
  profiles:
    active: local

  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    generate-ddl: true # hibernate에 스키마 생성 위임
    show-sql: false
    hibernate:
      ddl-auto: create-drop # 프로젝트 실행 시 테이블 생성 및 종료 시 삭제
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 기본 TTL 10분(ms)
      cache-null-values: false
      use-key-prefix: true

  data:
    redis:
      host: localhost
      port: 6379

  redis:
    redisson:
      file: classpath:redisson-single.yml

---
spring.config.activate.on-profile: local, test

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application